version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin --quiet
  
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongodb:27017/

  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    profiles: [run]
    volumes:
      - .:$PWD
    working_dir: $PWD
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env.local
    command: ["sh","-c","air"]